    
language: go

sudo: false

go:
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - 1.11
  - 1.12

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 2e09ffbb-f104-4552-b464-000efc4ca0c8
